name: TabDisplay
version: '${project.version}'
main: net.kjnine.tabdisplay.TabDisplay
api-version: 1.19
author: KJNine
website: https://github.com/KJNine/TabDisplay
commands:
  tab:
    description: Subscribes to the TPS tab-display
    permission: tabdisplay.tab
permissions:
  tabdisplay.tab:
    default: true